### ISSUE TITLE
Spark charm hook failed: "install"

### ISSUE THREAD

**Issue by Barteus** [canonical/spark-operator#11]
When installing the Spark using `juju deploy ch:spark` spark app errors with message `hook failed: "install"`

```
$ juju status
Model     Controller  Cloud/Region        Version  SLA          Timestamp
kubeflow  micro       microk8s/localhost  2.9.22   unsupported  15:16:18+01:00

App    Version  Status  Scale  Charm  Store     Channel  Rev  OS      Address  Message
spark           error       1  spark  charmhub  stable    73  ubuntu           hook failed: "install"

Unit      Workload  Agent  Address  Ports  Message
spark/0*  error     idle                   hook failed: "install"
```

```
$ juju debug-log
application-spark: 15:14:44 WARNING unit.spark/0.install     basic.bootstrap_charm_deps()
application-spark: 15:14:44 WARNING unit.spark/0.install   File "/var/lib/juju/agents/unit-spark-0/charm/lib/charms/layer/basic.py", line 52, in bootstrap_charm_deps
application-spark: 15:14:44 WARNING unit.spark/0.install     apt_install([
application-spark: 15:14:44 WARNING unit.spark/0.install   File "/var/lib/juju/agents/unit-spark-0/charm/lib/charms/layer/basic.py", line 187, in apt_install
application-spark: 15:14:44 WARNING unit.spark/0.install     check_call(cmd + packages, env=env)
application-spark: 15:14:44 WARNING unit.spark/0.install   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
application-spark: 15:14:44 WARNING unit.spark/0.install     raise CalledProcessError(retcode, cmd)
application-spark: 15:14:44 WARNING unit.spark/0.install subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'python3-pip', 'python3-setuptools', 'python3-yaml', 'python3-dev']' returned non-zero exit status 100.
application-spark: 15:14:44 ERROR juju.worker.caasoperator.uniter.spark/0.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
application-spark: 15:14:44 INFO juju.worker.caasoperator.uniter.spark/0 awaiting error resolution for "install" hook
application-spark: 15:14:32 INFO juju.worker.caasoperator.uniter.spark/0 awaiting error resolution for "install" hook
application-spark: 15:14:33 INFO juju.worker.caasoperator.uniter.spark/0 awaiting error resolution for "install" hook
application-spark: 15:14:34 WARNING unit.spark/0.install E: Package 'python3-dev' has no installation candidate
application-spark: 15:14:39 WARNING unit.spark/0.install E: Package 'python3-dev' has no installation candidate
application-spark: 15:14:44 WARNING unit.spark/0.install E: Package 'python3-dev' has no installation candidate
application-spark: 15:14:44 WARNING unit.spark/0.install Traceback (most recent call last):
application-spark: 15:14:44 WARNING unit.spark/0.install   File "/var/lib/juju/agents/unit-spark-0/charm/hooks/install", line 8, in <module>
```

Environment:
**juju version:** 2.9.22-ubuntu-amd64
**microk8s:** v1.21.9
```
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    metallb              # Loadbalancer for your Kubernetes cluster
    storage              # Storage class; allocates storage from host directory
```
The same was replicated on AKS.

**Comment by DomFleischmann** [comment]
The charm that is in charmhub under `ch:spark` is not the same charm like the one in this repository. Like this #10 issue mentiones this charm hasn't been uploaded to charmhub. Please use a locally built version of it for now.
